environment:
  zip_file: ""

init:
- ps: Update-AppveyorBuild -Version "$(Get-Date -format yyyy.MM.dd).$env:appveyor_build_number"
- ps: $env:zip_file = "$(Get-Date -format yyyyMMdd)-$env:appveyor_build_number"

platform: Any CPU

configuration:
- Release

image: Visual Studio 2019

nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: true
  
before_build:
- nuget restore CardQuery.sln

build_script:
- msbuild CardQuery.sln /v:minimal /p:ResolveNuGetPackages=false "/logger:%ProgramFiles%\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%\CardQuery\bin\%configuration%\
  - rm -r CardQuery.pdb
  - rm -r Newtonsoft.Json.xml
  - cd ..
  - mv %configuration% CardQuery
  - 7z a CardQuery-%zip_file%.zip .\CardQuery
  - cp CardQuery-%zip_file%.zip ..\..\CardQuery-%zip_file%.zip

for:
- branches:
    except:
      - master
  artifacts:
    #nothing
- branches:
    only:
      - master
  artifacts:
    - path: CardQuery-%zip_file%.zip
      name: CardQuery %zip_file% %APPVEYOR_REPO_BRANCH% binaries